### ISSUE TITLE
ERROR TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by seeramzan** [timkinnane/hubot-rocketchat-welcome#3]
Hi,

Thanks for your great efforts, i am a newbie , could you please guide on following error.

[Wed Dec 18 2019 08:39:24 GMT+0000 (UTC)] DEBUG Loading external-scripts from npm packages
[Wed Dec 18 2019 08:39:24 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/node_modules/hubot-links/src/hubot-links.coffee
[Wed Dec 18 2019 08:39:24 GMT+0000 (UTC)] INFO Welcome script is running, will send to any new users saying:
[Wed Dec 18 2019 08:39:24 GMT+0000 (UTC)] INFO "Welcome, I'm @bot. If you need help just reply with `help`"
[Wed Dec 18 2019 08:39:24 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/node_modules/hubot-chatops-help/src/hubot-rocketchat-welcome
[Wed Dec 18 2019 08:39:24 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/node_modules/hubot-help/src/help.coffee
[Wed Dec 18 2019 08:39:24 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/node_modules/hubot-seen/src/seen.coffee
[Wed Dec 18 2019 08:39:24 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/node_modules/hubot-diagnostics/src/diagnostics.coffee
[Wed Dec 18 2019 08:39:25 GMT+0000 (UTC)] DEBUG Parsing help for /home/hubot/node_modules/hubot-jira-bot/src/index.coffee
[Wed Dec 18 2019 08:41:02 GMT+0000 (UTC)] INFO Message received with ID id
[Wed Dec 18 2019 08:41:02 GMT+0000 (UTC)] INFO Message receive callback id we9RJQbSaNaLJv4xb ts Wed Dec 18 2019 08:41:02 GMT+0000 (UTC)
[Wed Dec 18 2019 08:41:02 GMT+0000 (UTC)] INFO [Incoming] uuser4: uuser4
[Wed Dec 18 2019 08:41:02 GMT+0000 (UTC)] INFO Checking to see if method: getRoomNameById exists
[Wed Dec 18 2019 08:41:02 GMT+0000 (UTC)] INFO Looking up Room Name for: GENERAL
[Wed Dec 18 2019 08:41:02 GMT+0000 (UTC)] INFO setting roomName: general
[Wed Dec 18 2019 08:41:02 GMT+0000 (UTC)] INFO Message sent to hubot brain.
[Wed Dec 18 2019 08:41:02 GMT+0000 (UTC)] DEBUG Executing listener callback for Message '[object Object]'
[Wed Dec 18 2019 08:41:02 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'length' of null
    at /home/hubot/node_modules/hubot-chatops-help/src/hubot-rocketchat-welcome:49:16
    at userIsKnown (/home/hubot/node_modules/hubot-chatops-help/src/hubot-rocketchat-welcome:49:11)
    at welcomeUser (/home/hubot/node_modules/hubot-chatops-help/src/hubot-rocketchat-welcome:64:13)
    at Listener.callback (/home/hubot/node_modules/hubot-chatops-help/src/hubot-rocketchat-welcome:75:5)
    at /home/hubot/node_modules/hubot/src/listener.coffee:65:12
    at allDone (/home/hubot/node_modules/hubot/src/middleware.coffee:44:37)
    at /home/hubot/node_modules/hubot/node_modules/async/lib/async.js:274:13
    at Object.async.eachSeries (/home/hubot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
    at Object.async.reduce (/home/hubot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
    at /home/hubot/node_modules/hubot/src/middleware.coffee:49:13
    at nextTickCallbackWith0Args (node.js:489:9)
    at process._tickCallback (node.js:418:13)

**Comment by timkinnane** [comment]
Sorry, I haven't worked on this for 3 years. No idea what's going on.
